---
- hosts: all
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Loadbalancers assignment

  import_playbook: ../static-assignments/loadbanlancers.yml

  when: load_balancer_is_required
